export type FolkRegion = "ru" | "lv" | "world";

export const FOLK_REGIONS: { id: FolkRegion; label: string }[] = [
  { id: "ru", label: "Русские" },
  { id: "lv", label: "Latviešu" },
  { id: "world", label: "Ещё все знают" },
];

export const FOLK_RAW: Array<{
  id: string;
  title: string;
  artist: string;
  region: FolkRegion;
  bpm: number;
  key: number;
  mood: string;
  beatsPerLine: number;
  texts: string[];
}> = [
  {
    id: "bereza",
    title: "Во поле берёза стояла",
    artist: "народная",
    region: "ru",
    bpm: 96,
    key: 55,
    mood: "хоровод",
    beatsPerLine: 8,
    texts: [
      "Во поле берёза стояла",
      "Во поле кудрявая стояла",
      "Люли, люли, стояла",
      "Люли, люли, стояла",
      "Некому берёзу заломати",
      "Некому кудряву заломати",
      "Я пойду берёзу заломаю",
      "Я пойду кудряву заломаю",
      "Люли, люли, заломаю",
      "Люли, люли, заломаю",
    ],
  },
  {
    id: "seni",
    title: "Ах вы сени, мои сени",
    artist: "народная",
    region: "ru",
    bpm: 126,
    key: 57,
    mood: "пляска",
    beatsPerLine: 4,
    texts: [
      "Ах вы сени, мои сени",
      "Сени новые мои",
      "Сени новые, кленовые",
      "Решётчатые",
      "Как бы мне, младой, младешеньке",
      "Сени новые пройти",
      "Сени новые, кленовые",
      "Решётчатые",
      "Вышла я на сени новые",
      "Сени новые прошла",
    ],
  },
  {
    id: "kalinka",
    title: "Калинка",
    artist: "народная",
    region: "ru",
    bpm: 152,
    key: 60,
    mood: "пляска",
    beatsPerLine: 4,
    texts: [
      "Калинка, калинка, калинка моя",
      "В саду ягода малинка, малинка моя",
      "Ах, под сосною, под зелёною",
      "Спать положите вы меня",
      "Ай-люли, люли, ай-люли, люли",
      "Спать положите вы меня",
      "Калинка, калинка, калинка моя",
      "В саду ягода малинка, малинка моя",
      "Ах, сосёнушка, ты зелёная",
      "Не шуми же надо мной",
    ],
  },
  {
    id: "korobushka",
    title: "Коробейники",
    artist: "Некрасов, 1861",
    region: "ru",
    bpm: 144,
    key: 62,
    mood: "ярмарка",
    beatsPerLine: 4,
    texts: [
      "Ой, полна, полна коробушка",
      "Есть и ситцы и парча",
      "Пожалей, душа-зазнобушка",
      "Молодецкого плеча",
      "Выйди, выйди в рожь высокую",
      "Там до ночки погодим",
      "А завидят нас прохожие",
      "Нас зазря не разлучат",
      "Ой, полна, полна коробушка",
      "Есть и ситцы и парча",
    ],
  },
  {
    id: "razin",
    title: "Из-за острова на стрежень",
    artist: "народная",
    region: "ru",
    bpm: 88,
    key: 53,
    mood: "река",
    beatsPerLine: 8,
    texts: [
      "Из-за острова на стрежень",
      "На простор речной волны",
      "Выплывают расписные",
      "Стеньки Разина челны",
      "Посредине Стенька Разин",
      "Обнявшись с княжною",
      "Свадьбу новую справляет",
      "Сам весёлый и хмельной",
      "А она, потупив очи",
      "Ни жива и ни мертва",
    ],
  },
  {
    id: "ochi",
    title: "Очи чёрные",
    artist: "Гребёнка, XIX в.",
    region: "ru",
    bpm: 72,
    key: 52,
    mood: "романс",
    beatsPerLine: 8,
    texts: [
      "Очи чёрные, очи страстные",
      "Очи жгучие и прекрасные",
      "Как люблю я вас, как боюсь я вас",
      "Знать, увидел вас я в недобрый час",
      "Очи чёрные, очи жгучие",
      "Очи страстные и прекрасные",
      "Если б я не встретил вас",
      "Я б спокойно прожил век",
      "Очи чёрные, очи страстные",
      "Вы сгубили меня напрасно",
    ],
  },
  {
    id: "voron",
    title: "Чёрный ворон",
    artist: "казачья народная",
    region: "ru",
    bpm: 84,
    key: 50,
    mood: "поле",
    beatsPerLine: 8,
    texts: [
      "Чёрный ворон, чёрный ворон",
      "Что ты вьёшься надо мной",
      "Ты добычи не дождёшься",
      "Чёрный ворон, я не твой",
      "Полети ты в край родимый",
      "Передай ты мой поклон",
      "Отцу с матерью печальной",
      "И подруженьке моей",
      "Чёрный ворон, чёрный ворон",
      "Я ещё постою",
    ],
  },
  {
    id: "yablochko",
    title: "Яблочко",
    artist: "народная",
    region: "ru",
    bpm: 138,
    key: 57,
    mood: "матросская",
    beatsPerLine: 4,
    texts: [
      "Эх, яблочко, да на тарелочке",
      "Кого люблю я, того нет боле",
      "Эх, яблочко, да куда котишься",
      "Кому мил-сердечный, тому и достанешься",
      "Эх, яблочко, да соку спелого",
      "Полюбил я девку из-за белого",
      "Эх, яблочко, да на тарелочке",
      "Кого люблю я, того нет боле",
    ],
  },
  {
    id: "sad",
    title: "Во саду ли в огороде",
    artist: "народная",
    region: "ru",
    bpm: 108,
    key: 55,
    mood: "хоровод",
    beatsPerLine: 8,
    texts: [
      "Во саду ли в огороде",
      "Девица гуляла",
      "Никого не полюбила",
      "Сама речь держала",
      "Вы подруженьки, голубушки",
      "Вы подруги милые",
      "Вы скажите, как мне быть",
      "Сердце не унять",
      "Во саду ли в огороде",
      "Девица гуляла",
    ],
  },
  {
    id: "kuznitsa",
    title: "Во кузнице",
    artist: "народная",
    region: "ru",
    bpm: 132,
    key: 57,
    mood: "пляска",
    beatsPerLine: 4,
    texts: [
      "Во кузнице, во кузнице",
      "Молоты стучат",
      "Ай люли, ай люли",
      "Молоты стучат",
      "Молоты стучат",
      "Работают ребята",
      "Ай люли, ай люли",
      "Работают ребята",
      "Во кузнице, во кузнице",
      "Огни горят",
    ],
  },
  {
    id: "riga-dimd",
    title: "Rīga dimd",
    artist: "latviešu tautas",
    region: "lv",
    bpm: 118,
    key: 60,
    mood: "Rīga",
    beatsPerLine: 4,
    texts: [
      "Rīga dimd, Rīga dimd",
      "Kas to Rīgu dimdināj",
      "Kas to Rīgu dimdināj",
      "Aiz visiem kungiem",
      "Rīgu dimdināja",
      "Tēva, mātes puišalēns",
      "Tēva, mātes puišalēns",
      "Aiz visiem kungiem",
      "Rīga dimd, Rīga dimd",
      "Kas to Rīgu dimdināj",
    ],
  },
  {
    id: "gailitis",
    title: "Kur tu teci",
    artist: "latviešu tautas",
    region: "lv",
    bpm: 128,
    key: 62,
    mood: "gaita",
    beatsPerLine: 4,
    texts: [
      "Kur tu teci, gailīti mans",
      "Kur tu teci, rai rai rai",
      "Es tecēju pie meitām",
      "Pie meitām, rai rai rai",
      "Ko tu teici meitiņām",
      "Ko tu teici, rai rai rai",
      "Lai ceļājas, lai mostas",
      "Lai mostas, rai rai rai",
      "Kur tu teci, gailīti mans",
      "Kur tu teci, rai rai rai",
    ],
  },
  {
    id: "drunken-sailor",
    title: "Drunken Sailor",
    artist: "sea shanty",
    region: "world",
    bpm: 124,
    key: 50,
    mood: "shanty",
    beatsPerLine: 4,
    texts: [
      "What shall we do with a drunken sailor",
      "What shall we do with a drunken sailor",
      "What shall we do with a drunken sailor",
      "Early in the morning",
      "Way hay and up she rises",
      "Way hay and up she rises",
      "Way hay and up she rises",
      "Early in the morning",
      "Put him in the longboat till he's sober",
      "Early in the morning",
    ],
  },
  {
    id: "auld-lang-syne",
    title: "Auld Lang Syne",
    artist: "Burns / народная",
    region: "world",
    bpm: 84,
    key: 53,
    mood: "toast",
    beatsPerLine: 8,
    texts: [
      "Should auld acquaintance be forgot",
      "And never brought to mind",
      "Should auld acquaintance be forgot",
      "And auld lang syne",
      "For auld lang syne, my dear",
      "For auld lang syne",
      "We'll take a cup of kindness yet",
      "For auld lang syne",
    ],
  },
  {
    id: "susanna",
    title: "Oh! Susanna",
    artist: "Foster, 1848",
    region: "world",
    bpm: 140,
    key: 57,
    mood: "banjo",
    beatsPerLine: 8,
    texts: [
      "I come from Alabama with a banjo on my knee",
      "I'm going to Louisiana, my true love for to see",
      "It rained all night the day I left, the weather it was dry",
      "The sun so hot I froze to death, Susanna don't you cry",
      "Oh, Susanna, don't you cry for me",
      "I come from Alabama with a banjo on my knee",
      "Oh, Susanna, don't you cry for me",
      "I come from Alabama with a banjo on my knee",
    ],
  },
  {
    id: "clementine",
    title: "Oh My Darling Clementine",
    artist: "народная, XIX в.",
    region: "world",
    bpm: 108,
    key: 55,
    mood: "camp",
    beatsPerLine: 4,
    texts: [
      "In a cavern, in a canyon",
      "Excavating for a mine",
      "Dwelt a miner forty-niner",
      "And his daughter Clementine",
      "Oh my darling, oh my darling",
      "Oh my darling Clementine",
      "You are lost and gone forever",
      "Dreadful sorry, Clementine",
    ],
  },
  {
    id: "saints",
    title: "When the Saints Go Marching In",
    artist: "spiritual",
    region: "world",
    bpm: 112,
    key: 60,
    mood: "new orleans",
    beatsPerLine: 4,
    texts: [
      "Oh when the saints go marching in",
      "Oh when the saints go marching in",
      "Oh Lord I want to be in that number",
      "When the saints go marching in",
      "Oh when the sun begins to shine",
      "Oh when the sun begins to shine",
      "Oh Lord I want to be in that number",
      "When the saints go marching in",
    ],
  },
  {
    id: "cucaracha",
    title: "La Cucaracha",
    artist: "mexicana tradicional",
    region: "world",
    bpm: 128,
    key: 62,
    mood: "fiesta",
    beatsPerLine: 4,
    texts: [
      "La cucaracha, la cucaracha",
      "Ya no puede caminar",
      "Porque no tiene, porque le falta",
      "Las patitas de atrás",
      "La cucaracha, la cucaracha",
      "Ya no puede caminar",
      "Porque no tiene, porque le falta",
      "Las patitas de atrás",
    ],
  },
  {
    id: "jingle",
    title: "Jingle Bells",
    artist: "Pierpont, 1857",
    region: "world",
    bpm: 138,
    key: 65,
    mood: "sleigh",
    beatsPerLine: 4,
    texts: [
      "Dashing through the snow",
      "In a one-horse open sleigh",
      "O'er the fields we go",
      "Laughing all the way",
      "Jingle bells, jingle bells",
      "Jingle all the way",
      "Oh what fun it is to ride",
      "In a one-horse open sleigh",
    ],
  },
  {
    id: "bonnie",
    title: "My Bonnie Lies Over the Ocean",
    artist: "народная",
    region: "world",
    bpm: 92,
    key: 55,
    mood: "sea",
    beatsPerLine: 8,
    texts: [
      "My Bonnie lies over the ocean",
      "My Bonnie lies over the sea",
      "My Bonnie lies over the ocean",
      "Oh bring back my Bonnie to me",
      "Bring back, bring back",
      "Bring back my Bonnie to me, to me",
      "Bring back, bring back",
      "Oh bring back my Bonnie to me",
    ],
  },
];
