/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHostAudioRouteImport } from './routes/api/host-audio'
import { Route as ApiSunoAudioRouteImport } from './routes/api/suno-audio'
import { Route as ApiSunoHookRouteImport } from './routes/api/suno-hook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHostAudioRoute = ApiHostAudioRouteImport.update({
  id: '/api/host-audio',
  path: '/api/host-audio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSunoAudioRoute = ApiSunoAudioRouteImport.update({
  id: '/api/suno-audio',
  path: '/api/suno-audio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSunoHookRoute = ApiSunoHookRouteImport.update({
  id: '/api/suno-hook',
  path: '/api/suno-hook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/host-audio': typeof ApiHostAudioRoute
  '/api/suno-audio': typeof ApiSunoAudioRoute
  '/api/suno-hook': typeof ApiSunoHookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/host-audio': typeof ApiHostAudioRoute
  '/api/suno-audio': typeof ApiSunoAudioRoute
  '/api/suno-hook': typeof ApiSunoHookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/host-audio': typeof ApiHostAudioRoute
  '/api/suno-audio': typeof ApiSunoAudioRoute
  '/api/suno-hook': typeof ApiSunoHookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/host-audio' | '/api/suno-audio' | '/api/suno-hook'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/host-audio' | '/api/suno-audio' | '/api/suno-hook'
  id:
    '__root__' | '/' | '/api/host-audio' | '/api/suno-audio' | '/api/suno-hook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiHostAudioRoute: typeof ApiHostAudioRoute
  ApiSunoAudioRoute: typeof ApiSunoAudioRoute
  ApiSunoHookRoute: typeof ApiSunoHookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/host-audio': {
      id: '/api/host-audio'
      path: '/api/host-audio'
      fullPath: '/api/host-audio'
      preLoaderRoute: typeof ApiHostAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/suno-audio': {
      id: '/api/suno-audio'
      path: '/api/suno-audio'
      fullPath: '/api/suno-audio'
      preLoaderRoute: typeof ApiSunoAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/suno-hook': {
      id: '/api/suno-hook'
      path: '/api/suno-hook'
      fullPath: '/api/suno-hook'
      preLoaderRoute: typeof ApiSunoHookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiHostAudioRoute: ApiHostAudioRoute,
  ApiSunoAudioRoute: ApiSunoAudioRoute,
  ApiSunoHookRoute: ApiSunoHookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
