/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHostAudioRouteImport } from './routes/api/host-audio'
import { Route as ApiSunoAudioRouteImport } from './routes/api/suno-audio'
import { Route as ApiSunoHookRouteImport } from './routes/api/suno-hook'
import { Route as ApiVkPayRouteImport } from './routes/api/vk-pay'
import { Route as ApiVkSessionRouteImport } from './routes/api/vk-session'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHostAudioRoute = ApiHostAudioRouteImport.update({
  id: '/api/host-audio',
  path: '/api/host-audio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSunoAudioRoute = ApiSunoAudioRouteImport.update({
  id: '/api/suno-audio',
  path: '/api/suno-audio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSunoHookRoute = ApiSunoHookRouteImport.update({
  id: '/api/suno-hook',
  path: '/api/suno-hook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVkPayRoute = ApiVkPayRouteImport.update({
  id: '/api/vk-pay',
  path: '/api/vk-pay',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVkSessionRoute = ApiVkSessionRouteImport.update({
  id: '/api/vk-session',
  path: '/api/vk-session',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/host-audio': typeof ApiHostAudioRoute
  '/api/suno-audio': typeof ApiSunoAudioRoute
  '/api/suno-hook': typeof ApiSunoHookRoute
  '/api/vk-pay': typeof ApiVkPayRoute
  '/api/vk-session': typeof ApiVkSessionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/host-audio': typeof ApiHostAudioRoute
  '/api/suno-audio': typeof ApiSunoAudioRoute
  '/api/suno-hook': typeof ApiSunoHookRoute
  '/api/vk-pay': typeof ApiVkPayRoute
  '/api/vk-session': typeof ApiVkSessionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/host-audio': typeof ApiHostAudioRoute
  '/api/suno-audio': typeof ApiSunoAudioRoute
  '/api/suno-hook': typeof ApiSunoHookRoute
  '/api/vk-pay': typeof ApiVkPayRoute
  '/api/vk-session': typeof ApiVkSessionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/host-audio'
    | '/api/suno-audio'
    | '/api/suno-hook'
    | '/api/vk-pay'
    | '/api/vk-session'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/host-audio'
    | '/api/suno-audio'
    | '/api/suno-hook'
    | '/api/vk-pay'
    | '/api/vk-session'
  id:
    | '__root__'
    | '/'
    | '/api/host-audio'
    | '/api/suno-audio'
    | '/api/suno-hook'
    | '/api/vk-pay'
    | '/api/vk-session'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiHostAudioRoute: typeof ApiHostAudioRoute
  ApiSunoAudioRoute: typeof ApiSunoAudioRoute
  ApiSunoHookRoute: typeof ApiSunoHookRoute
  ApiVkPayRoute: typeof ApiVkPayRoute
  ApiVkSessionRoute: typeof ApiVkSessionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/host-audio': {
      id: '/api/host-audio'
      path: '/api/host-audio'
      fullPath: '/api/host-audio'
      preLoaderRoute: typeof ApiHostAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/suno-audio': {
      id: '/api/suno-audio'
      path: '/api/suno-audio'
      fullPath: '/api/suno-audio'
      preLoaderRoute: typeof ApiSunoAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/suno-hook': {
      id: '/api/suno-hook'
      path: '/api/suno-hook'
      fullPath: '/api/suno-hook'
      preLoaderRoute: typeof ApiSunoHookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vk-pay': {
      id: '/api/vk-pay'
      path: '/api/vk-pay'
      fullPath: '/api/vk-pay'
      preLoaderRoute: typeof ApiVkPayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vk-session': {
      id: '/api/vk-session'
      path: '/api/vk-session'
      fullPath: '/api/vk-session'
      preLoaderRoute: typeof ApiVkSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiHostAudioRoute: ApiHostAudioRoute,
  ApiSunoAudioRoute: ApiSunoAudioRoute,
  ApiSunoHookRoute: ApiSunoHookRoute,
  ApiVkPayRoute: ApiVkPayRoute,
  ApiVkSessionRoute: ApiVkSessionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
