/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiClipRouteImport } from './routes/api/clip'
import { Route as ApiDoorRouteImport } from './routes/api/door'
import { Route as ApiHostRouteImport } from './routes/api/host'
import { Route as ApiHostAudioRouteImport } from './routes/api/host-audio'
import { Route as ApiPaintRouteImport } from './routes/api/paint'
import { Route as ApiSunoAudioRouteImport } from './routes/api/suno-audio'
import { Route as ApiSunoHookRouteImport } from './routes/api/suno-hook'
import { Route as ApiVkIdRouteImport } from './routes/api/vk-id'
import { Route as ApiVkPayRouteImport } from './routes/api/vk-pay'
import { Route as ApiVkSessionRouteImport } from './routes/api/vk-session'
import { Route as ApiYookassaRouteImport } from './routes/api/yookassa'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClipRoute = ApiClipRouteImport.update({
  id: '/api/clip',
  path: '/api/clip',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDoorRoute = ApiDoorRouteImport.update({
  id: '/api/door',
  path: '/api/door',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHostRoute = ApiHostRouteImport.update({
  id: '/api/host',
  path: '/api/host',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHostAudioRoute = ApiHostAudioRouteImport.update({
  id: '/api/host-audio',
  path: '/api/host-audio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaintRoute = ApiPaintRouteImport.update({
  id: '/api/paint',
  path: '/api/paint',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSunoAudioRoute = ApiSunoAudioRouteImport.update({
  id: '/api/suno-audio',
  path: '/api/suno-audio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSunoHookRoute = ApiSunoHookRouteImport.update({
  id: '/api/suno-hook',
  path: '/api/suno-hook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVkIdRoute = ApiVkIdRouteImport.update({
  id: '/api/vk-id',
  path: '/api/vk-id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVkPayRoute = ApiVkPayRouteImport.update({
  id: '/api/vk-pay',
  path: '/api/vk-pay',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVkSessionRoute = ApiVkSessionRouteImport.update({
  id: '/api/vk-session',
  path: '/api/vk-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYookassaRoute = ApiYookassaRouteImport.update({
  id: '/api/yookassa',
  path: '/api/yookassa',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/clip': typeof ApiClipRoute
  '/api/door': typeof ApiDoorRoute
  '/api/host': typeof ApiHostRoute
  '/api/host-audio': typeof ApiHostAudioRoute
  '/api/paint': typeof ApiPaintRoute
  '/api/suno-audio': typeof ApiSunoAudioRoute
  '/api/suno-hook': typeof ApiSunoHookRoute
  '/api/vk-id': typeof ApiVkIdRoute
  '/api/vk-pay': typeof ApiVkPayRoute
  '/api/vk-session': typeof ApiVkSessionRoute
  '/api/yookassa': typeof ApiYookassaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/clip': typeof ApiClipRoute
  '/api/door': typeof ApiDoorRoute
  '/api/host': typeof ApiHostRoute
  '/api/host-audio': typeof ApiHostAudioRoute
  '/api/paint': typeof ApiPaintRoute
  '/api/suno-audio': typeof ApiSunoAudioRoute
  '/api/suno-hook': typeof ApiSunoHookRoute
  '/api/vk-id': typeof ApiVkIdRoute
  '/api/vk-pay': typeof ApiVkPayRoute
  '/api/vk-session': typeof ApiVkSessionRoute
  '/api/yookassa': typeof ApiYookassaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/clip': typeof ApiClipRoute
  '/api/door': typeof ApiDoorRoute
  '/api/host': typeof ApiHostRoute
  '/api/host-audio': typeof ApiHostAudioRoute
  '/api/paint': typeof ApiPaintRoute
  '/api/suno-audio': typeof ApiSunoAudioRoute
  '/api/suno-hook': typeof ApiSunoHookRoute
  '/api/vk-id': typeof ApiVkIdRoute
  '/api/vk-pay': typeof ApiVkPayRoute
  '/api/vk-session': typeof ApiVkSessionRoute
  '/api/yookassa': typeof ApiYookassaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/clip'
    | '/api/door'
    | '/api/host'
    | '/api/host-audio'
    | '/api/paint'
    | '/api/suno-audio'
    | '/api/suno-hook'
    | '/api/vk-id'
    | '/api/vk-pay'
    | '/api/vk-session'
    | '/api/yookassa'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/clip'
    | '/api/door'
    | '/api/host'
    | '/api/host-audio'
    | '/api/paint'
    | '/api/suno-audio'
    | '/api/suno-hook'
    | '/api/vk-id'
    | '/api/vk-pay'
    | '/api/vk-session'
    | '/api/yookassa'
  id:
    | '__root__'
    | '/'
    | '/api/clip'
    | '/api/door'
    | '/api/host'
    | '/api/host-audio'
    | '/api/paint'
    | '/api/suno-audio'
    | '/api/suno-hook'
    | '/api/vk-id'
    | '/api/vk-pay'
    | '/api/vk-session'
    | '/api/yookassa'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiClipRoute: typeof ApiClipRoute
  ApiDoorRoute: typeof ApiDoorRoute
  ApiHostRoute: typeof ApiHostRoute
  ApiHostAudioRoute: typeof ApiHostAudioRoute
  ApiPaintRoute: typeof ApiPaintRoute
  ApiSunoAudioRoute: typeof ApiSunoAudioRoute
  ApiSunoHookRoute: typeof ApiSunoHookRoute
  ApiVkIdRoute: typeof ApiVkIdRoute
  ApiVkPayRoute: typeof ApiVkPayRoute
  ApiVkSessionRoute: typeof ApiVkSessionRoute
  ApiYookassaRoute: typeof ApiYookassaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clip': {
      id: '/api/clip'
      path: '/api/clip'
      fullPath: '/api/clip'
      preLoaderRoute: typeof ApiClipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/door': {
      id: '/api/door'
      path: '/api/door'
      fullPath: '/api/door'
      preLoaderRoute: typeof ApiDoorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/host': {
      id: '/api/host'
      path: '/api/host'
      fullPath: '/api/host'
      preLoaderRoute: typeof ApiHostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/host-audio': {
      id: '/api/host-audio'
      path: '/api/host-audio'
      fullPath: '/api/host-audio'
      preLoaderRoute: typeof ApiHostAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paint': {
      id: '/api/paint'
      path: '/api/paint'
      fullPath: '/api/paint'
      preLoaderRoute: typeof ApiPaintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/suno-audio': {
      id: '/api/suno-audio'
      path: '/api/suno-audio'
      fullPath: '/api/suno-audio'
      preLoaderRoute: typeof ApiSunoAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/suno-hook': {
      id: '/api/suno-hook'
      path: '/api/suno-hook'
      fullPath: '/api/suno-hook'
      preLoaderRoute: typeof ApiSunoHookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vk-id': {
      id: '/api/vk-id'
      path: '/api/vk-id'
      fullPath: '/api/vk-id'
      preLoaderRoute: typeof ApiVkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vk-pay': {
      id: '/api/vk-pay'
      path: '/api/vk-pay'
      fullPath: '/api/vk-pay'
      preLoaderRoute: typeof ApiVkPayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vk-session': {
      id: '/api/vk-session'
      path: '/api/vk-session'
      fullPath: '/api/vk-session'
      preLoaderRoute: typeof ApiVkSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/yookassa': {
      id: '/api/yookassa'
      path: '/api/yookassa'
      fullPath: '/api/yookassa'
      preLoaderRoute: typeof ApiYookassaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiClipRoute: ApiClipRoute,
  ApiDoorRoute: ApiDoorRoute,
  ApiHostRoute: ApiHostRoute,
  ApiHostAudioRoute: ApiHostAudioRoute,
  ApiPaintRoute: ApiPaintRoute,
  ApiSunoAudioRoute: ApiSunoAudioRoute,
  ApiSunoHookRoute: ApiSunoHookRoute,
  ApiVkIdRoute: ApiVkIdRoute,
  ApiVkPayRoute: ApiVkPayRoute,
  ApiVkSessionRoute: ApiVkSessionRoute,
  ApiYookassaRoute: ApiYookassaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
